id: SIGMA-LIN-AUDITING_CONFIGURATI
title: Auditing Configuration Changes on Linux Host
category: audit
subcategory: detection
mitre_technique: T1562.006
mitre_tactic: ''
severity: high
confidence: low
enabled: true
description: Detect changes in auditd configuration files
service: auditd
detection:
  type: pattern
  patterns:
  - regex: PATH
  - regex: /etc/audit/.*
  - regex: /etc/libaudit\.conf
  - regex: /etc/audisp/.*
false_positives:
- Legitimate administrative activity
recommendation: 'Review the activity matching this rule. Original Sigma rule: rules/linux/auditd/path/lnx_auditd_auditing_config_change.yml.
  References: https://github.com/Neo23x0/auditd/blob/master/audit.rules, Self Experience'
references:
- https://github.com/Neo23x0/auditd/blob/master/audit.rules
- Self Experience
tags:
- attack.defense-evasion
- attack.t1562.006
_sigma_source: rules/linux/auditd/path/lnx_auditd_auditing_config_change.yml
_sigma_status: test
_sigma_author: Mikhail Larin, oscd.community
_sigma_date: 2019-10-25
